import { NotificationCategory, NotificationType } from "../../../prisma/generated/client";
import type { EmailTemplate } from "../../lib/notifications/email/email.interface";
import type { NotifyChannel } from "./notification.service";

export interface NotificationEventDefinition {
    type: NotificationType;
    label: string;
    description: string;
    category: NotificationCategory;
    defaultChannels: NotifyChannel[];
    emailTemplate: EmailTemplate | null;
    variables: string[];
}

export const NOTIFICATION_EVENT_CATALOG: Record<NotificationType, NotificationEventDefinition> = {
    SELLER_APPROVED: {
        type: "SELLER_APPROVED",
        label: "Seller account approved",
        description: "Sent to a seller when their account application is approved.",
        category: "ACCOUNT",
        defaultChannels: ["email", "sse"],
        emailTemplate: "seller-approved",
        variables: ["sellerName", "businessName", "loginUrl"],
    },
    SELLER_REJECTED: {
        type: "SELLER_REJECTED",
        label: "Seller account rejected",
        description: "Sent to a seller when their account application is rejected.",
        category: "ACCOUNT",
        defaultChannels: ["email", "sse"],
        emailTemplate: "seller-rejected",
        variables: ["sellerName", "businessName", "reason"],
    },
    PRODUCT_APPROVED: {
        type: "PRODUCT_APPROVED",
        label: "Product approved",
        description: "Sent to a seller when a submitted product is approved.",
        category: "ACCOUNT",
        defaultChannels: ["email", "sse"],
        emailTemplate: "product-approved",
        variables: ["sellerName", "productName", "dashboardUrl", "note"],
    },
    PRODUCT_REJECTED: {
        type: "PRODUCT_REJECTED",
        label: "Product rejected",
        description: "Sent to a seller when a submitted product is rejected.",
        category: "ACCOUNT",
        defaultChannels: ["email", "sse"],
        emailTemplate: "product-rejected",
        variables: ["sellerName", "productName", "reason"],
    },
    ORDER_PLACED: {
        type: "ORDER_PLACED",
        label: "Order placed",
        description: "Sent to a customer when their order is placed successfully.",
        category: "ORDER",
        defaultChannels: ["email", "sms", "sse"],
        emailTemplate: "order-placed",
        variables: ["customerName", "orderId", "orderType", "items", "totalAmount", "orderUrl"],
    },
    ORDER_CONFIRMED: {
        type: "ORDER_CONFIRMED",
        label: "Order confirmed",
        description: "Sent to a customer when their order is confirmed by the seller.",
        category: "ORDER",
        defaultChannels: ["email", "sse"],
        emailTemplate: "order-confirmed",
        variables: ["customerName", "orderId", "finalAmount", "orderUrl"],
    },
    ORDER_CANCELLED: {
        type: "ORDER_CANCELLED",
        label: "Order cancelled",
        description: "Sent to a customer when their order is cancelled.",
        category: "ORDER",
        defaultChannels: ["email", "sse"],
        emailTemplate: "order-cancelled",
        variables: ["customerName", "orderId", "orderUrl"],
    },
    SHIPMENT_UPDATED: {
        type: "SHIPMENT_UPDATED",
        label: "Shipment status update",
        description: "Sent to a customer whenever their shipment's tracking status changes.",
        category: "SHIPMENT",
        defaultChannels: ["email", "sms", "sse"],
        emailTemplate: "shipment-updated",
        variables: ["customerName", "orderId", "status", "trackingId", "trackingUrl", "estimatedDelivery"],
    },
    PAYMENT_RECEIVED: {
        type: "PAYMENT_RECEIVED",
        label: "Payment received",
        description: "In-app only alert when a payment is captured for an order.",
        category: "PAYOUT",
        defaultChannels: ["sse"],
        emailTemplate: null,
        variables: [],
    },
    KYC_VERIFIED: {
        type: "KYC_VERIFIED",
        label: "KYC verified",
        description: "Sent to a seller when their KYC documents are verified. Non-disableable - KYC status directly gates payout eligibility.",
        category: "SECURITY",
        defaultChannels: ["email", "sse"],
        emailTemplate: "kyc-verified",
        variables: ["sellerName", "dashboardUrl"],
    },
    KYC_REJECTED: {
        type: "KYC_REJECTED",
        label: "KYC rejected",
        description: "Sent to a seller when their KYC documents are rejected. Non-disableable - KYC status directly gates payout eligibility.",
        category: "SECURITY",
        defaultChannels: ["email", "sse"],
        emailTemplate: "kyc-rejected",
        variables: ["sellerName", "reason", "dashboardUrl"],
    },
    RETURN_REQUESTED: {
        type: "RETURN_REQUESTED",
        label: "Return requested",
        description: "Sent to a seller when a customer raises a return request.",
        category: "ORDER",
        defaultChannels: ["email", "sse"],
        emailTemplate: "return-requested",
        variables: ["sellerName", "orderId", "returnUrl"],
    },
    RETURN_APPROVED: {
        type: "RETURN_APPROVED",
        label: "Return approved",
        description: "Sent to a customer when their return request is approved.",
        category: "ORDER",
        defaultChannels: ["email", "sse"],
        emailTemplate: "return-approved",
        variables: ["customerName", "orderId", "trackingId", "trackingUrl", "returnUrl"],
    },
    RETURN_REJECTED: {
        type: "RETURN_REJECTED",
        label: "Return rejected",
        description: "Sent to a customer when their return request is rejected.",
        category: "ORDER",
        defaultChannels: ["email", "sse"],
        emailTemplate: "return-rejected",
        variables: ["customerName", "orderId", "reason", "returnUrl"],
    },
    PAYOUT_INITIATED: {
        type: "PAYOUT_INITIATED",
        label: "Payout initiated",
        description: "Sent to a seller when a payout is initiated for them.",
        category: "PAYOUT",
        defaultChannels: ["email", "sse"],
        emailTemplate: "payout-initiated",
        variables: ["sellerName", "businessName", "netAmount", "payoutUrl"],
    },
    PAYOUT_PAID: {
        type: "PAYOUT_PAID",
        label: "Payout successful",
        description: "Sent to a seller when a payout is successfully transferred.",
        category: "PAYOUT",
        defaultChannels: ["email", "sse"],
        emailTemplate: "payout-paid",
        variables: ["sellerName", "netAmount", "utrRef", "payoutUrl"],
    },
    PAYOUT_FAILED: {
        type: "PAYOUT_FAILED",
        label: "Payout failed",
        description: "Sent to a seller when a payout transfer fails.",
        category: "PAYOUT",
        defaultChannels: ["email", "sse"],
        emailTemplate: "payout-failed",
        variables: ["sellerName", "netAmount", "failureReason", "payoutUrl"],
    },
    PRODUCT_LOW_STOCK: {
        type: "PRODUCT_LOW_STOCK",
        label: "Low stock alert",
        description: "Sent to a seller when a product/SKU's stock crosses below its low-stock threshold.",
        category: "ACCOUNT",
        defaultChannels: ["email", "sse"],
        emailTemplate: "low-stock",
        variables: ["sellerName", "productName", "currStock", "threshold", "productUrl"],
    },
    REVIEW_RECEIVED: {
        type: "REVIEW_RECEIVED",
        label: "Review received",
        description: "In-app only alert to a seller when a customer leaves a review on their product.",
        category: "ACCOUNT",
        defaultChannels: ["sse"],
        emailTemplate: null,
        variables: [],
    },
    REVIEW_REPLY: {
        type: "REVIEW_REPLY",
        label: "Review reply",
        description: "Reserved for notifying a customer when a seller replies to their review. Not yet triggered anywhere in the codebase.",
        category: "ACCOUNT",
        defaultChannels: [],
        emailTemplate: null,
        variables: [],
    },
    COUPON_APPLIED: {
        type: "COUPON_APPLIED",
        label: "Coupon applied",
        description: "Reserved for notifying a customer their coupon was applied. Not yet triggered anywhere in the codebase.",
        category: "PROMOTION",
        defaultChannels: [],
        emailTemplate: null,
        variables: [],
    },
    TEAM_INVITE: {
        type: "TEAM_INVITE",
        label: "Team invite",
        description: "Sent to an invited team member (or reminder for a still-pending invite).",
        category: "ACCOUNT",
        defaultChannels: ["email", "sse"],
        emailTemplate: "team-invite",
        variables: ["businessName", "roleName", "inviteUrl", "isReminder"],
    },
    NEGOTIATION_NUDGE: {
        type: "NEGOTIATION_NUDGE",
        label: "Negotiation nudge",
        description: "Sent to a customer whose negotiation didn't conclude: either an AUTO session that ended REJECTED (nudging them toward manual negotiation), or a MANUAL session that went stale/EXPIRED from inactivity (low-pressure reminder the item's still available).",
        category: "NEGOTIATION",
        defaultChannels: ["email", "sse"],
        emailTemplate: "negotiation-nudge",
        variables: ["reason", "customerName", "productName", "quantity", "lastOfferedPrice", "visiblePrice", "negotiationUrl"],
    },
    MANUAL_NEGOTIATION_STARTED: {
        type: "MANUAL_NEGOTIATION_STARTED",
        label: "Manual negotiation started",
        description: "Sent to a seller when a customer starts a manual negotiation session.",
        category: "NEGOTIATION",
        defaultChannels: ["email", "sse"],
        emailTemplate: "manual-negotiation-started",
        variables: ["sellerName", "productName", "quantity", "negotiationUrl"],
    },
};

export const TYPE_TO_CATEGORY: Record<NotificationType, NotificationCategory> = Object.fromEntries(
    Object.values(NOTIFICATION_EVENT_CATALOG).map((def) => [def.type, def.category]),
) as Record<NotificationType, NotificationCategory>;
