export const PERMISSIONS = {
    PRODUCTS_CREATE: "products.create",
    PRODUCTS_UPDATE: "products.update",
    PRODUCTS_DELETE: "products.delete",
    PRODUCTS_VIEW: "products.view",
    PRODUCTS_BULK: "products.bulk",
    PRODUCTS_EXPORT: "products.export",
    PRODUCTS_IMAGES: "products.images.manage",
    PRODUCTS_VARIANTS: "products.variants.manage",
    SELLER_KYC: "seller.kyc.manage",
    SELLER_BANK: "seller.bank.manage",
    SELLER_MEMBERS_VIEW: "seller.members.view",
    SELLER_MEMBERS_MANAGE: "seller.members.manage",
    SELLER_ROLES_MANAGE: "seller.roles.manage",
    SELLER_INVITES_MANAGE: "seller.invites.manage",
    NEGOTIATIONS_RESPOND: "negotiations.respond",
    ANALYTICS_VIEW: "analytics.view",
    SELLER_PROFILE_MANAGE: "seller.profile.manage",
    SELLER_GST_MANAGE: "seller.gst.manage",
    SELLER_VERIFICATION_MANAGE: "seller.verification.manage",
    SELLER_VERIFICATION_VIEW: "seller.verification.view",
    RETURNS_VIEW: "returns.view",
    RETURNS_MANAGE: "returns.manage",
    SHOPS_VIEW: "shops.view",
    SHOPS_MANAGE: "shops.manage",
    SHOPS_ADMIN: "shops.admin",
    CUSTOMIZATION_VIEW: "customization.view",
    CUSTOMIZATION_MANAGE: "customization.manage",
    ORDERS_FULFILL: "orders.fulfill",
    ORDERS_MANAGE: "orders.manage",
    ORDERS_ADMIN: "orders.admin",
    SHIPMENTS_VIEW: "shipments.view",
    SHIPMENTS_MANAGE: "shipments.manage",
    REVIEWS_VIEW: "reviews.view",
    REVIEWS_MANAGE: "reviews.manage",
    INVOICES_MANAGE: "invoices.manage",
} as const;

export type PermissionKey = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];

export const PLATFORM_PERMISSIONS = {
    PLATFORM_SELLERS_VIEW_LIST: "platform.sellers.view_list",
    PLATFORM_SELLERS_VIEW_DETAIL: "platform.sellers.view_detail",
    PLATFORM_SELLERS_INVITE: "platform.sellers.invite",
    PLATFORM_SELLERS_APPROVE: "platform.sellers.approve",
    PLATFORM_SELLERS_REJECT: "platform.sellers.reject",
    PLATFORM_SELLERS_SUSPEND: "platform.sellers.suspend",
    PLATFORM_SELLERS_KYC_REVIEW: "platform.sellers.kyc_review",
    PLATFORM_SELLERS_BANK_OVERRIDE: "platform.sellers.bank_override",
    PLATFORM_SELLERS_GST_PAN_OVERRIDE: "platform.sellers.gst_pan_override",
    PLATFORM_VERIFICATION_REVIEW: "platform.verification.review",
    PLATFORM_ANALYTICS_VIEW: "platform.analytics.view",
    PLATFORM_ANALYTICS_REFRESH: "platform.analytics.refresh",
    PLATFORM_COUPONS_VIEW: "platform.coupons.view",
    PLATFORM_COUPONS_MANAGE: "platform.coupons.manage",
    PLATFORM_CATEGORIES_MANAGE: "platform.categories.manage",
    PLATFORM_ORDERS_VIEW_ALL: "platform.orders.view_all",
    PLATFORM_ORDERS_SET_COMMISSION: "platform.orders.set_commission",
    PLATFORM_ORDERS_ASSIGN: "platform.orders.assign",
    PLATFORM_PAYOUTS_CONFIG: "platform.payouts.config",
    PLATFORM_PAYOUTS_VIEW: "platform.payouts.view",
    PLATFORM_PAYOUTS_INITIATE: "platform.payouts.initiate",
    PLATFORM_PRODUCTS_VIEW: "platform.products.view",
    PLATFORM_PRODUCTS_APPROVE: "platform.products.approve",
    PLATFORM_PRODUCTS_REJECT: "platform.products.reject",
    PLATFORM_PRODUCTS_SET_COMMISSION: "platform.products.set_commission",
    PLATFORM_NEGOTIATIONS_VIEW: "platform.negotiations.view",
    PLATFORM_REVIEWS_MODERATE: "platform.reviews.moderate",
    PLATFORM_SHIPMENTS_VIEW: "platform.shipments.view",
    PLATFORM_SHOPS_VIEW: "platform.shops.view",
    PLATFORM_USERS_VIEW: "platform.users.view",
    PLATFORM_ADMIN_ROLES_MANAGE: "platform.admin_roles.manage",
    PLATFORM_ADMIN_MEMBERS_MANAGE: "platform.admin_members.manage",
    PLATFORM_AUDIT_LOGS_VIEW: "platform.audit_logs.view",
    PLATFORM_INVOICES_VIEW: "platform.invoices.view",
    PLATFORM_NOTIFICATIONS_VIEW: "platform.notifications.view",
    PLATFORM_NOTIFICATIONS_MANAGE: "platform.notifications.manage",
    PLATFORM_RETURNS_VIEW: "platform.returns.view",
    PLATFORM_PAYMENTS_CONFIG: "platform.payments.config",
    PLATFORM_PAYMENTS_RECORD_MANUAL: "platform.payments.record_manual",
} as const;

export type PlatformPermissionKey = (typeof PLATFORM_PERMISSIONS)[keyof typeof PLATFORM_PERMISSIONS];

export function isPlatformPermissionKey(key: string): key is PlatformPermissionKey {
    return key.startsWith("platform.");
}